### ISSUE TITLE
[공통] Preview Provider 생성

### ISSUE THREAD

**Issue by Taehyeon-Kim** [TeamOOTD/OOTD-iOS#5]
### 💡 요약
- SwiftUI의 Preview Provider 기능을 이용해서 코드 베이스 작업을 더 편리하게 합니다.

### ✅ 체크리스트
> 해야 할 일을 적어주세요 :)
- [x] Device 열거형 생성
- [x] Preview Provider 생성

**Comment by pcsoyeon** [comment]
기대되네요 ..
